### ISSUE TITLE
The docker image latest is old version

### ISSUE THREAD

**Issue by zengzhengrong** [k0sproject/k0s#2323]
```
unknown command "controller" for "k0s"
```
```
zengzhengrong@cengzhengrongdeMac-mini ~ % docker images
REPOSITORY       TAG       IMAGE ID       CREATED         SIZE
nginx            latest    605c77e624dd   10 months ago   141MB
k0sproject/k0s   latest    da974a2ed2a3   22 months ago   220MB
```

**Comment by jnummelin** [comment]
Yes, this is unfortunately a known issue. We stopped at some point to publish `latest` releases since that alias has more problems than positives in general. By using `latest` one will stumble on versioning issues sooner or later as you have no real knowledge what `latest` mean at a given time.

When we dropped that from k0s release pipeline unfortunately we did not remove the `latest` tags completely. We're planning now to completely remove `latest` from images and update docs accordingly.

So instead of using `latest`, we **strongly** suggest to use real version tags, e.g. [`v1.25.2-k0s.0`](https://hub.docker.com/layers/k0sproject/k0s/v1.25.2-k0s.0/images/sha256-0939cc40803e93d0039ad9cb9d539342f171eecf5195c972d8d804d5e07fa013?context=repo)
