### ISSUE TITLE
K0S doesn't have external dependencies properly documented

### ISSUE THREAD

**Issue by juanluisvaladas** [k0sproject/k0s#2473]
As @twz123 pointed out in https://github.com/k0sproject/k0s/pull/2468/files#r1037500311 k0s uses `cp` and this dependency is not documented.

After a quick grep I found a bunch of calls to external tools which are not documented or shipped in k0s binary. I also found references to other commands which are not documented either and some unlike cp aren't part of coreutils:
- userdel or userdel (I beleive the only call to userdel will fallback to deluser if it fails)
- adduser
- modprobe
- id
- cp

**Comment by twz123** [comment]
Some notes on the things I know:

`modprobe`: it is at least part of `k0s sysinfo`, and it's not strictly required, but rather used to make k0s more convenient to use.
`id`: This is a fallback in case "regular" user lookup fails, because, for example, NSS is being used, which requires dynamic linking, which in turn is somewhat at odds with k0s's philosophy.

**Comment by ncopa** [comment]
`adduser`/`useradd` is only used for install. You can create the user account manually or run all parts of k0s as root. So `adduser` is not a hard requirement either.
 
`deluser`/`userdel` is only used with `k0s reset` which is a convenience function to uninstall k0s. Also not a hard requirement.

`cp` is used for backup/restore, so it is also not a hard requirement. I think we should replace this with something implemented in go.

**Comment by makhov** [comment]
Here is a go package for this in case we don't want to implement it ourselves: https://github.com/otiai10/copy
