### ISSUE TITLE
Introduce support to Istio

### ISSUE THREAD

**Issue by brunoarruda** [k0sproject/k0s#2517]
### Is your feature request related to a problem? Please describe.

I want to use a service mesh in my on-promise Kubernetes, and Istio was my choice. I made a PoC with k0s and had to use Traefik instead of istio for Ingress Controller. The PoC went well, but my company discarted k0s as istio became the standard ingress for all projects inside it and i had to move to Racher Kubernetes.

### Describe the solution you would like

It would be nice if k0s supported istio.

### Describe alternatives you've considered

As I said, I used Traefik for my PoC but the final result was rejected. As the official documentation doesn't offer an option to install istio (docs only refer to Nginx and Traefik), I haven't tried to install it.

### Additional context

I don't know the complexities underlying this issue. I searched on Google and Github for some information of why k0s doesn't  support Istio as Ingress, but found none. If this subject was addressed in some discussion, please reply here with the link to make it more visible for others.

**Comment by juanluisvaladas** [comment]
You can install istio on top of k0s, or at least it's the expected behavior. In fact there is a blog post showing istio on top of k0s: https://www.mirantis.com/blog/more-service-mesh-info/

Keep in mind that "you can install istio on top  of k0s" is not the same as "k0s supports istio", I'm not making any statement on the current or future supportability of istio and being deliberately vague.
