### ISSUE TITLE
Suggestion: Stage kubectl to the /var/lib/k0s/pki

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#291]
Now we have kubeconfig staged as /var/lib/mke/pki/admin.conf

If we would stage kubectl binary there as well, the bootstrap process would be even easier (now the end user either should already have kubctl installed or install it manually) and the cluster could be used right after mke worker joined.

**Comment by Matthew-Beckett** [comment]
> > > How about a `mke kubectl-config` that dumps the config to stdout?
> > 
> > 
> > but we have already a KUBECONFIG under `/var/lib/mke/pki/admin.conf` what would a separate command achieve?
> 
> Would make it "easier" to find the config. End user would not need to remember where its stored.
> 
> I agree it is a weak argument. 🙂

As an extension to this, it being called admin.conf is a little confusing and not documented in the README as part of the getting started, this issue was the first mention I found that admin.conf was a Kubeconfig as usually it's named such.

Maybe not worth adding the ability to make a Kubeconfig, but maybe putting it somewhere less hidden away or with a slightly better name would be beneficial in my opinion.

**Comment by jnummelin** [comment]
Another option for this is to enable something like `k0s kubectl get node` by compiling the kubectl into k0s binary itself as a subcommand. That will put the correct kubeconfig envs etc in place for kubectl.

By compiling it into k0s bin itself I think we're going to save on couple things:
- we already depend on quite a few client-go bits so should not cause that much increase in bin size
- no need to spawn another process for kubectl (if done by embedding the separate bin) and copying I/O etc.
-
