### ISSUE TITLE
containerd config location is "wrong"

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#3430]
When k0s manages the containerD config it currently uses containerD default location which is `/etc/...`. k0s stores pretty much all other info under `/var/lib/k0s/...` so it would be much better to manage the containerd config there too. This provides users more friendly place for containerd configs too as the data-dir is configurable.

Some additional care needs to be done to make sure the "migration" is handled well in case of upgrades.

Reference: https://github.com/k0sproject/k0sctl/issues/512

**Comment by twz123** [comment]
> When k0s manages the containerD config it currently uses containerD default location which is `/etc/...`.

To be precise, k0s doesn't use containerd's default config directory, which is `/etc/containerd`. It rather uses its own default config directory, `/etc/k0s`.

> k0s stores pretty much all other info under `/var/lib/k0s/...` so it would be much better to manage the containerd config there too.

After some thought, I'd say the current location is _actually the right place_. The `containerd.toml` file and the `containerd.d` folder contain user-editable configuration data, so it makes perfect sense to have them in the same directory as k0s's `config.yaml`. From this point of view, user-managed manifests could be stored under `/etc/k0s/manifests/` instead of `/var/lib/k0s/manifests/`. This would also clearly separate user-managed manifests from k0s-managed manifests.

> This provides users more friendly place for containerd configs too as the data-dir is configurable.

Right, there should be a way for users to change the paths, although I'm not quite sure what the best way would be. Conceptually, k0s currently has a configurable data directory (defaults to `/var/lib/k0s`), a non-configurable run directory (`/run/k0s`, other software might call this the state directory), and a non-configurable config directory (`/etc/k0s`). This is essentially an idiomatic FHS layout.

I can think of these possibilities:

1. K0s has its `--config` flag for the config file. We could say that the config directory is the directory where the config file is located, meaning that `containerd.toml` and `containerd.d` would also be placed in that directory.
2. Have some knob for the config dir with the usual suspects as source (config file, environment variable, CLI flag). However, would this mean that the default config file location would also change if you had support for getting it from an environment variable or CLI flag and did not provide the `--config` flag?
3. Don't make the config dir configurable per se, but provide knobs for individual config locations.

I'd also consider how this applies to the run directory. I think this should eventually be configurable too, probably in the same way as the config directory.

Note: The XDG Base Directory specification defines well-known environment variables to override default directory locations. It's not directly applicable to k0s, though. (It would be if k0s had a rootless mode.)
