### ISSUE TITLE
`k0s user create`

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#389]
**Is your feature request related to a problem? Please describe.**

By default k0s configures only cert based auth for API server and only the `admin.conf` with cluster admin role bound to it.

We should make available some subcommand to easily create a new cert and kubeconfig for a new user.

**Describe the solution you'd like**
`k0s user create jussi --group foo,bar`

That would dump out a kubeconfig with embedded certs for a user called `jussi`. In the cert there's groups for `foo` and `bar`.

**Describe alternatives you've considered**

**Additional context**

**Comment by binoychitale** [comment]
Hi @jnummelin , I would like to have a go at this issue (since it is labeled as a good first issue).
From what I understand, we would need to do the following:

1. Create a cobra subcommand for the "user create" functionality 
2. Within this new subcommand, we would create a signed certificate (using the existing certificate library within the project) + pub key.
3.  Dump the **certificate** and **public key** into a kubeConfig template (the way its being done for admin.conf) and write it to stdout.

Does this look right to you? If yes, can I begin implementing the same?

Thanks.

**Comment by jnummelin** [comment]
@binoychitale That sounds like exactly what I've had in mind for this. 👍 

One thing we need to make clear both in docs and in command description is that there's absolutely no way to revoke those certs. That's just how kube works currently.
