### ISSUE TITLE
Issue running up the K0s worker

### ISSUE THREAD

**Issue by lchunleo** [k0sproject/k0s#4084]
k0s airgap bundle : v1.29.1+k0s.1
air-gap environment: RHEL 8

Setup: Separate controller and worker node
Issue: "failed to load TOML:  /run/k0s/containerd-cri.toml open /run/k0s/containerd-cri.toml no such file and directory"

How it happen:  Above happens when perform:
1) k0s install worker --token-file xxx.txt where xxx.txt contains the generated token
2) k0s start
The error message is generated when 
i have place the airgap bundle in the directory /var/lib/k0s/images  but i unsure i need to do anything more on this. When the problem still persists i gathered all the required tar files and even go to the extent to load it but still the same.

Am it assumed that i need to install the containerd in the worker node myself and not assuming the bundle will install for me?

the documentation has spelled clear steps controller but not the worker. Thus would like to have some advice how to properly do a manual setup for worker in air gap environment. Thanks

**Comment by twz123** [comment]
Are you able to share the full k0s worker logs, so that we can try to figure out what's happening? The error string is coming from containerd not being able to find its k0s-generated config file. Have you checked that `/run/k0s/containerd-cri.toml` actually exists on the file system? If k0s fails to create that file, it's expected to terminate itself with the appropriate error written to stderr.

**Comment by twz123** [comment]
> Am it assumed that i need to install the containerd in the worker node myself and not assuming the bundle will install for me?

In it's default setup, k0s will use the containerd that's bundled with k0s. No need to install it. In fact, even if it is installed, k0s won't use the system-wide containerd unless the appropriate config switches are provided.

> the documentation has spelled clear steps controller but not the worker. Thus would like to have some advice how to properly do a manual setup for worker in air gap environment. Thanks

Which part of the documentation are you referring to? Since controllers don't run any containers, there's not much to do for them in an airgapped environment. It's only the workers (and controllers with workloads enabled) that need to be seeded with airgap bundles. Did you have a look at the [Airgap install](https://docs.k0sproject.io/v1.29.1+k0s.1/airgap-install/) docs page? What kind of information are you looking for that is missing from that page? It essentially boils down to: "Place the airgap bundle into \<k0s-data-dir\>/images (the default is /var/lib/k0s/images) and k0s will automatically load the images in there into containerd."
