### ISSUE TITLE
Question: Is it possible to put the control plane behind a load-balancer?

### ISSUE THREAD

**Issue by amdonov** [k0sproject/k0s#455]
I've only done limited testing, so please forgive me if I've overlooked something that should have been obvious.

In our current configuration (not k0s just upstream k8s), our k8s masters are behind a load-balancer. New nodes communicate with the load-balancer to join the cluster and masters can come and go. I'd like to have a similar configuration with k0s, but I've hit a problem.

It seems like the token generation code is tied to the value of the API address in the k0s configuration file. I'm running in AWS and tried to use the DNS name of an elastic load-balancer. However, it complained that it wasn't an IP. If I don't set it, it gets the IP of the host and new nodes must communicate with a specific master to join. Is that correct? If so, do you have suggestions on automating adding nodes that that doesn't assume the initial control plane node is always available? We rebuild all of our servers fairly frequently.

**Comment by jnummelin** [comment]
I actually did test k0s behind a LB and had it working. But I did it in environment where the LB actually has an IP address and thus did not hit into this issue. 🤦 

The problem with ELB is that the `spec.api.address` from k0s config is passed as-is to kube-apiserver as `--advertise-address` flag. And that does not take anything else than a plain IP. 😠 

We could probably workaround this by having another attribute for LB type of address which would be used in tokens and other needed places. So something like:
```
spec:
  api:
    lbAddress: my-lb.com
    address: 1.2.3.4
    sans:
    - my-lb.com
    - 1.2.3.4
    - 2.3.4.5
```

The only problem that would still remain is the fact that I cannot figure out a way to make the LB address to be used in `kubernetes` service for "in-cluster" communications. So kube-apiserver always populates the service endpoints based on this `--advertise-address` flag (and if not given at all it'll default to first IP on the node).  With the above example config the in-cluster `kubernetes` endpoint would still look something like:
```
# kubectl get ep kubernetes
NAME         ENDPOINTS           AGE
kubernetes   1.2.3.4:6443,2.3.4.5:6443   23m
```

That would essentially mean that even when LB is in front of k0s controllers, the nodes will still need direct connectivity to controller IPs too.

> our k8s masters are behind a load-balancer. New nodes communicate with the load-balancer to join the cluster and masters can come and go.

Given the fact how kupe-api manages the `kubernetes` in-cluster svc endpoints, I'd assume your workers still have direct connectivity to the masters IPs?

**Comment by jnummelin** [comment]
@amdonov I'm tinkering with something to tackle this, would appreciate your input on the direction from user perspective. :)

So the config qould look something like:
```
spec:
  api:
    address: 1.2.3.4
    externalAddress: my-lb.somedomain.com
    sans:
      - my-lb.somedomain.com
```
For tokens we'd use the address `my-lb.somedomain.com`

So given that `my-lb.somedomain.com` resolves into addresses `10.1.1.1` and `20.2.2.2`, we'd get kubernetes cluster internal endpoint reconciled as:
```
# kubectl get ep kubernetes
NAME            ENDPOINTS                     AGE
kubernetes   10.1.1.1:6443,20.2.2.2:6443      23m
```

So the k0s controller would have a reconciliation loop to resolve and update, if needed, the LB addresses into kubernetes endpoint.

**Comment by amdonov** [comment]
Once nodes join, they bypass the ELB. That’s fine. They will still talk to
any available master. External clients can continue to use the ELB.

**Comment by jnummelin** [comment]
@amdonov I've cooked some enhancement on this in PR #527

Would be super nice if you can take a look at that and see if the approach suits your use case. And if possible even give it a spin.

**Comment by mbentley** [comment]
I was giving k0s 0.9.1 a try today and I am trying to understand some of the behavior of the `externalAddress` config that was added.  I have k0s working behind haproxy because I have multiple instances of k8s running at my house and i'm using SNI to route requests to specific k8s instances.  I noticed that when I set `externalAddress`, my nodes do not come up, assuming because per https://github.com/k0sproject/k0s/pull/527, it ends up resolving the specified LB address to an IP.  In my case, that would resolve to my home IP but then it wouldn't have any SNI info which means that haproxy routes requests to the default backend (in my case, that is the wrong backend k8s cluster).  Is there any specific reason why it needs to resolve to the addresses?  I verified this by changing the default backend pool to my k0s cluster and then everything went healthy.

**Comment by jnummelin** [comment]
With `externalAddress` set few things happen:
- the given address is used as the join address in tokens. The address is used as-is and thus should go through SNI
- Kubelet is configured to connect to the API using the given address
- in-cluster components (kube-proxy, konnectivity-agent) that connect to the API directly are configured to connect to the given address
- API is started with `endpoint-reconciler-type=none` setting, means that API itself does not populate the endpoints of `kubernetes` service, k0s reconciler resolves the given address to IPs and syncs the endpoints
- all in-cluster components connecting via `kubernetes` svc will call to one of the resolved endpoint IPs (via kube-proxy iptables)

@mbentley I'm assuming that calico does not get properly up as it cannot connect to the API via the in-cluster svc?

I could imagine introducing yet-another flag for this to disable the custom endpoint reconciler. With that disabled, the kube svc endpoint would be populated by the API "instances" with the address given to each in `api.address` field. Just like it behaves now. That would by-pass the LB (HAProxy in this case) for "in-cluster" API calls. But of course would require that there is a direct connectivity from the worker to the API.

**Comment by mbentley** [comment]
That makes sense as to what I am seeing then.  That's correct, none of the Calico pods come up until either the default backend pool of my k0s k8s API server is the default or I disable the `externalAddress` value.  In my use case, all of my nodes can communicate with each other on the internal private network.  I'm basically just looking for an option that would allow the cluster to realize that users will hit it at the external address so that things like config files are generated with the appropriate FQDN and I'd expect certs to be set up appropriately for an external FQDN as well in that case without having to specify the SANs in the config.

I initially looking at the config option and was just thinking of my use case, not where nodes would need to communicate to the API because they're not running on the same internal network but that's just because that is how my set up is.
