### ISSUE TITLE
Command `user` not found

### ISSUE THREAD

**Issue by ctron** [k0sproject/k0s#461]
**Version**
```
v0.7.0
```
**Platform**
Which platform did you run k0s on?
```
root@ubuntu:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

```
**What happened?**

Running `k0s user`, as described by the documentation, fails:

~~~
root@ubuntu:/home/ubuntu# k0s user
Error: unknown command "user" for "k0s"
Run 'k0s --help' for usage.
unknown command "user" for "k0s"
2020-11-26 15:19:56.132239 I | unknown command "user" for "k0s"
~~~

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

Run `k0s user`.

**Expected behavior**

Documentation does not contain command that do not exist.

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

**Additional context**

**Comment by trawler** [comment]
Hi @ctron, thanks for opening this issue!
our docs are evolving all the time, along with code changes. So the `docs` you see in master may be different than our latest release, and will likely refer to the version in `master`.
In order to view the docs at the time the release was "baked" you can use a tagged link, for example: https://github.com/k0sproject/k0s/tree/v0.7.0

**Comment by ctron** [comment]
Maybe it would help then not pointing people by default to the "master" branch?!

**Comment by trawler** [comment]
That's a valid point. We'll take this into consideration 👍
