### ISSUE TITLE
How to configure FelixConfiguration custom resource ?

### ISSUE THREAD

**Issue by zig** [k0sproject/k0s#5359]
When using Calico with K0S, is it safe to modify the custom resource with kind `FelixConfiguration` (named `default`), or will k0s overwrite it  ? 

What component created that resource ?  K0S or calico itself ? Is there any way to configure it at cluster creation ?

**Comment by juanluisvaladas** [comment]
Hi @zig 

K0s doesn't overwrite it. The `default` `FelixConfiguration` object is created and managed by calico exclusively. K0s per se doesn't create, modify or read the object, it's the `calico-kube-controllers`. [You can check in the code exactly what k0s does](https://github.com/k0sproject/k0s/tree/release-1.31/static/manifests/calico) and everything else is. done by calico.

Regarding if it's safe or not, I don't want to say "it's safe" because I don't want anyone modifying the object like it doesn't have consequences because a k0s developer said it's safe to modify :). Obviously modifying this has risks because you're modifying the calico configuration, but we can say it's as safe to modify as if you had deployed calico yourself.

> Is there any way to configure it at cluster creation ?

You can use k0s's [manifest deployer](https://docs.k0sproject.io/v1.31.3+k0s.0/manifests/).

**Comment by zig** [comment]
Thanks for the answer !
