### ISSUE TITLE
Does it use less resource than k8s? What are the differences between k0s and k3s? 

### ISSUE THREAD

**Issue by orange888** [k0sproject/k0s#581]
Hi,
I ran across your project and have a few questions.
1. k8s requires quite a bit of resource, esp. on the manager node(s). A lot of people use k3s on pi or ioT devices. Does k0s use less resource? How does it compare against k3s? What are the hardware requirements?

2. In your web, you have mentioned something that is related to security. Could you publish or blog about what those means and the corresponding results?
```
CIS security benchmark
FIPS 140-2
```

Thank you!

**Comment by jnummelin** [comment]
> Does k0s use less resource?

Most of the resource consumption comes from kube components (api, etcd) so k0s is pretty much "bound" to those. (as is k3s). k0s has slightly more "overhead" as we run all the kube components as "naked" processes instead of everything  bundled in a single process.

> What are the hardware requirements?

As for any kube master, for k0s server  2G mem, 2 CPU should be fine for a smaller cluster. Depends a bit of course wheter you run etcd or e.g. sqlite as the state storage. 

For workers the basic worker components (k0s, kubelet, kube-proxy, calico, etc.) take around 300M of mem. Rest is up to what your planning to run on the cluster. :)

> In your web, you have mentioned something that is related to security. Could you publish or blog about what those means and the corresponding results?

Yes, we're planning on releasing some blogs around these topics. For CIS benchmarks we've been running kube-bench but unfortunately we do not get very reliable results with it currently. It gives too many false positives. Thats definitely in our radar to look at and try get it to produce reliable results with k0s.

**Comment by tcurdt** [comment]
> k0s has slightly more "overhead" as we run all the kube components as "naked" processes instead of everything bundled in a single process.

So k3s is more lightweight than k0s? and the un-bundling of the processes would be the primary reason to use k0s over k3s?

**Comment by jnummelin** [comment]
> So k3s is more lightweight than k0s?

yes, in raw computing resources.

> the un-bundling of the processes would be the primary reason to use k0s over k3s?

I'd say the primary reason for running k0s is the added flexibility of running the controlplane fully isolated from workers. That enables you for more exotic deployment architectures where e.g. you can run the controllers in cloud and workers in private DC with only outbound connectivity. (to open the control tunnels from nodes to API). see more on this at: https://docs.k0sproject.io/main/architecture/

**Comment by tcurdt** [comment]
To amplify the exotic deployment scenario: Would it be possible to run the control plane behind a NAT on a RPi while the load balancer and workers run on whatever cloud provider I want? maybe even multi cloud?

**Comment by jnummelin** [comment]
>  Would it be possible to run the control plane behind a NAT on a RPi while the load balancer and workers run on whatever cloud provider I want?

as long as the workers (the konnectivity-agent daemonset) have single address to dial to and can connect to the proxy-server running on the controller(s) it _should_ work. Once this "reverse tunnel" is established, k0s configures kube api to use it when it needs to connect to the workers.

> maybe even multi cloud?

Multicloud is always bit difficult from the overlay network perspective. But theoretically there's no limits as long as Calico can establish the network between nodes in different clouds. You can always use custom CNI too if something else works better in these cases, but then it's fully up to you to configure the networking. We also have options to enable wireguard on calico which might make multicloud much easier

**Comment by jnummelin** [comment]
Closing as answered question.
