### ISSUE TITLE
Docs: Adding hardware installation requirements/recommendations

### ISSUE THREAD

**Issue by danmx** [k0sproject/k0s#682]
**Is your feature request related to a problem? Please describe.**

I'd like to know minimum and recommended CPU and Memory requirements to run `k0s` in different scenarios. It would help assessing the hardware e.g. when working with system boards like Jetson, Rasperry Pi, etc.

**Describe the solution you'd like**

Something like `k3s` [hardware requirements](https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#hardware).

**Describe alternatives you've considered**

I'd have to run tests myself.

**Comment by ncopa** [comment]
If you do run tests yourself, then please publish the results here :wink:

I think we need at least more than 1G disk space on the workers for the cluster to start up, in addition for the disk space needed for the work loads.

**Comment by mbehm** [comment]
I'd also be very much interested in hardware requirements/suggestions for the controller/master nodes with different amounts of worker nodes/pods etc.. For the actual workers since it'll mostly depend on the actual workloads I'm fine without, but some kind of minimum requirements would surely be helpful for people not already running local kubernetes testing environments etc.
