### ISSUE TITLE
Setup cluster behind a proxy

### ISSUE THREAD

**Issue by MicleMaslow** [k0sproject/k0s#754]
I can't set http_proxy, https_proxy, no_proxy for containerd. I have solution: set Environment in k0scontroller.service systemd unit. But this could be done after installing cluster with k0s/k0sctl. I need to install this during cluster installation. Is such a solution possible now or will it be added in the next version?

**Comment by jnummelin** [comment]
What if you set the proxy envs system-wide in `/etc/environment`? k0sctl does support this, see https://github.com/k0sproject/k0sctl#spechostsenvironment-mapping-optional

**Comment by MicleMaslow** [comment]
K0sctl sets k0s as systemd daemon. Systemd daemon doesn`t sup system env. It is supporting only Environment and EnvironmentFile parameters. K0sctl does support this, but only sets entries to /etc/environment. Pulling docker images after installed cluster doesn`t work with proxy.

**Comment by jnummelin** [comment]
@MicleMaslow thanks for the clarification, the intricacies of systemd details never stops to bring surprises :D

So maybe something like this could solve this:
```
k0s install controller ... -e http_proxy=1.2.3.4 -e no_proxy=localhost,foo,bar
```

WDYT?

**Comment by jewertow** [comment]
I will take this task.

**Comment by jewertow** [comment]
I investigated this issue more and I want to share the results of my research.

k0s supports systemd and OpenRC, but these systems work quite different, so this feature has to be implemented different for both systems.

1. Systemd - as @MicleMaslow said, it's possible to define environment variables directly in `.service` file as `Environment` parameters or to specify a file with environment variables as `EnvironmentFile` parameter.
2. OpenRC - as far as I know, there is no option to define environment variables in a script. I was experimenting with OpenRC and I found only 2 options to make environment variables visible for supervised processes:
- execute the following command: `HTTP_PROXY=1.2.3.4 /etc/init.d/<daemon_script> start`; it's important to notice that running `HTTP_PROXY=1.2.3.4 rc-service <daemon_script> start` will not make passed env visible for a process
- define export of env variable in `/etc/profile` and execute `source /etc/profile`

**Important:** to make those methods possible it's required to disable filtering environment variables in `/etc/rc.conf` by setting `rc_env_allow="*"`.

So I suggest to implement it as follows:
1. In case of systemd: create a file `etc/sysconfig/k0s` with specified env variables and add `EnvironmentFile=-/etc/sysconfig/k0s` entry to systemd configuration and then install.
2. In case of OpenRC: add env variables to `/etc/profile` (if exists) and execute `source /etc/profile` and then install.

If you agree to implement it this way, I can start implementation this week. Otherwise please suggest any alternative solution.
@jnummelin @ncopa @jasmingacic

**Comment by jasmingacic** [comment]
Since k0s supports reset which is supposed to remove all k0s remnants I would suggest that we don't leave anything in the OS that we cannot clean up. 

In case of SystemD we could parse CLI parametere `-e --envvars` and add it to template like this:
```
[Service]
Environment=SOMETHING=value
```
In case of openRC probably you would have to do something like:
```
command="ENV_VAR1=var1 ENV_VAR2=var2 some command"
```

Does this make sense?

Also for what is worth mentioning currently we are rethinking how the install command should work.

**Comment by jnummelin** [comment]
> Since k0s supports reset which is supposed to remove all k0s remnants I would suggest that we don't leave anything in the OS that we cannot clean up.

This is good point and really means we should not touch `/etc/profile` in any ways.

For systemd there's also [drop-in](https://wiki.archlinux.org/title/Systemd#Drop-in_files) option which IMO is the way to tackle these customization needs.

So IMO we should tackle this mostly in documentation side and not start to support X, Y and Z options for service units.

**Comment by jewertow** [comment]
Thank you for feedback. I will test an approach with drop-ins and if it works, I will add information to the docs.

**Comment by jewertow** [comment]
[Here](https://github.com/jewertow/k0s-sandbox/tree/master/cluster-behind-a-proxy) is an example of cluster behind a forward proxy. It proves that drop-ins work and in case of OpenRC it's required to export env variables directly in a service file.

**Comment by jewertow** [comment]
My conclusions were not right in case of OpenRC.

Installing with environment variables could be done by adding these variables to `command=ENV_VAR1=var1 ENV_VAR2=var2 k0s` (as @jasmingacic noticed) or by adding `export ENV_VAR1=var1` directly to the script (I was testing this approach). So in general it should be quite easy to implement and consistent with `Environment=` in systemd and it wouldn't be needed to touch any other file in the system.
