### ISSUE TITLE
versioning is whack

### ISSUE THREAD

**Issue by Raboo** [k0sproject/k0s#876]
Hi,

I definitely think that this new versioning is confusing, i.e. `k0s-v1.21.0+k0s.0-amd64`. The normal praxis is that you have something like this `k0s-v0.14.1-k8s_v1.21.0-amd64` and still follow the rules of sematic versioning.
Cause the "first" version (ex `v0.14.1`) reveals if it's stable or not, major, feature or bug fix release, etc... And the "second" version is the bundled application (k8s in this case)
You must also factor in the fact that you could have multiple releases with same k8s versions that deals with bugs native to k0s and not k8s, ex. `k0s-v0.14.2-k8s_v1.21.0-amd64`, `k0s-v0.14.3-k8s_v1.21.0-amd64`.

I propose that you switch back to a k0s versioning and suffix the k8s version, ex. `v0.14.2-k8s_v1.21.0`.
This also allows this project to support multiple k8s versions with the same k0s release, i.e. `v0.14.2-k8s_v1.21.0` and `v0.14.2-k8s_v1.20.0`

**Comment by matti** [comment]
https://twitter.com/ibuildthecloud/status/1381670157630599171

**Comment by Raboo** [comment]
Well I my point was not wether to use - or +, or dot vs no dot.

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
```

And my interpretation of semver is that k0s is the "\<version core\>" not k8s.
If you want to be strict about semver then it should be `k0s-v0.13.1+001`.
This project is not k8s, it's also not etcd, calico, etc.. I don't see the calico version in the release version string. This project is k0s, don't follow k3s mistakes. However I do recognize that k8s is a core component in k0s, thus my suggestion from above stands with a slight modification `v0.14.2+k8s_v1.21.0` and we can all pretend that `k8s_v1.21.0` is the build name.

**Comment by mviitane** [comment]
Hi Raboo, we decided to change the version numbering to make it easier to see the Kubernetes version from the version string. The kube version is such an important piece of information that it’s now the ruling part of the version string.

This also helps with the upgrade. It makes it easier for the users who want to stay in a certain Kubernetes minor version for a longer time to lock in (pin) to that Kubernetes version and just keep upgrading the other parts.

It also clarifies the support, because the support period is tight to the Kube version (as shown in the picture).

![image](https://user-images.githubusercontent.com/74129181/118975173-62d2d680-b97c-11eb-8358-eef26452bb6f.png)

**Comment by mviitane** [comment]
We published "k0s is ready for production" in our last blog post. Check this out:
https://medium.com/k0sproject/k0s-ready-for-production-20255c4b0791

In the Medium blog we try to update the community about new releases etc:
https://medium.com/k0sproject

**Comment by Raboo** [comment]
Ok, good to know. Perhaps then it's a good time to update the status section in the readme? https://github.com/k0sproject/k0s#status

**Comment by mviitane** [comment]
Thank you, very good point! I'll update the page.
