### ISSUE TITLE
When i restore a backup, i get localhost:6443 was refused.

### ISSUE THREAD

**Issue by krubenrc** [k0sproject/k0s#891]
Hello, im testing the new feature about backup and restore the controller node.

When i do the backup, y get this result:
![2021-05-06 09_24_41-root@master20_ ~](https://user-images.githubusercontent.com/33639842/117259513-67f93700-ae4e-11eb-9764-1b340d24d9a1.png)

But when i do the restore in a new server, when i start the controller service and i ask for the nodes or pods, i get an error:
![2021-05-06 09_31_04-root@master2_ ~](https://user-images.githubusercontent.com/33639842/117259650-8bbc7d00-ae4e-11eb-89a4-2058b9b0a759.png)

Too i tried install first the controller, and before start the service, restore the backup, but i get always the same error.
localhost:6443 was refused.

Can you help me please, if im doing something wrong, or is a bug?

**Comment by soider** [comment]
@krubenrc hello! I am really sorry for your inconvenience. 

That's most probably the file permissions value is the issue here. 
You can either manually run `chmod -R etcd:etcd /var/lib/k0s/etcd` to fix it, or run directly `k0s controller.

Root cause here is that when we run k0s by systemd unit, etcd uses it's own user "etcd" while backup is restored under the root user always.

The thing is that we can't be sure that "etcd" user exists during the restoration.

I will actually prepare the fix to ensure proper file permissions if the desired user exists AND modify the documentation making it mention the necessity of having "etcd" user avaiable by running prior `k0s install`.

**Comment by soider** [comment]
Should be fixed in PR #892, which is going to be the part of the next week release. Meanwhile please use one of the mentioned workarounds and don't hesitate to contact in case of any other issues.
