### ISSUE TITLE
Expected /var/lib/k0s permissions seem wrong

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#950]
k0s wants /var/lib/k0s to have `drwxr-xr-x`  and refuses to start if that is not the case.

I would think `drwxrwx---`  would make more sense 

- why let outsiders access the dir at all?
- allowing group to have full access is nice when you have it chowned for example `k0s:k0s` and add your regular user to that group. or `root:adm` or such.

**Comment by ncopa** [comment]
This is a can of worms. We run different services as different users, `etcd`, `kube-apiserver`, `kube-scheduler`, and `konnectivity-server`, which need to access things like CA certificates. Originally there was a `k0s` group which all those different users needed to belong to, but to keep things simple we did the top level dir `/var/lib/k0s` be world readable.

If we changes this, we need to make sure that the different users belongs to that group.

More, i generally think it is bad for security with too strict permissions on directories, because then you end up running everything as root, even when you don't really need that. (you'd need to run as root for the auto-complete to work for example).

**Comment by kke** [comment]
Ok that makes sense.
