### ISSUE TITLE
Question: Pre-pull images to be run in k0s

### ISSUE THREAD

**Issue by nanoandrew4** [k0sproject/k0s#965]
We are currently using k0s with helm to install helm charts for our integration test environment. We will be deleting and re-creating containers a lot, so I thought it would be a good idea to pre-pull some images that we commonly use in the helm charts in the Dockerfile so that charts would start faster, and we wouldn't be pulling so much data from dockerhub (since we do have limited pulls). Is there any way of doing this? `docker pull` won't work since docker isn't installed, so is there another way of doing this? Or is it all pointless because the images are stored somewhere on the host that the k0s docker image runs on, and aren't pulled each time we create a new k0s container and install some charts?

**Comment by jnummelin** [comment]
hmm, so you're running k0s "cluster" in a container in the CI runs?

If so, then one way is to push images as tarball bundles into the container. Or actually multiple of bundles, one for k0s system images and one for the application (the one you deploy with helm).

Once k0s worker (which is enabled by default on the k0s container image) boots it looks at `/var/lib/k0s/images` directory for  image bundles (==tarballs of exported images) and imports them to containerd on-the-fly*. You can get a pre-baked bundle for system images from k0s releases page. For your app level images you can use something like this to export them:
```
docker image save docker.io/myorg/myapp:1.2.3 docker.io/myorg/my-other-app:4.5.6 -o app_images.tar
```

This feature is designed for setting up airgapped envs, but works also in this sort of cases too. Read more at: https://docs.k0sproject.io/main/airgap-install/

> Or is it all pointless because the images are stored somewhere on the host that the k0s docker image runs on

The k0s in a (docker) container does NOT use the "host" docker so it does not see the host images. In theory it would be possible to configure it so that it does actually see the host docker, but that probably causes some trouble with cgroups etc.

*) Importing images is quite IO heavy naturally, so depending on the CI env you use, it might not actually be that much faster than pulling them. k0s CI is on Github actions and on there the savings on using pre-baked image bundle is actually quite small.

**Comment by nanoandrew4** [comment]
@jnummelin Thank you for the info! I think that will be the approach we will take, we are not terribly concerned with the IO cost of importing the images, we have other processes that take quite long before our tests can begin, and we'd save having to download them over and over again every time we create a new k0s container. 

Can we place gzipped tars in that directory, or only plain tars? Also, how can I validate that the tars have been processed and the images are loaded in the k0s container?

**Comment by jnummelin** [comment]
> Can we place gzipped tars in that directory, or only plain tars?

Plain tarballs only as that's the only supported input format for containerd. Internally we use containerd APIs for the import.

> how can I validate that the tars have been processed and the images are loaded in the k0s container?

k0s will NOT start kubelet until it has actually imported the images properly. Other than that there's no easy way currently. But having no kubelet running should prevent from scheduling the workloads until the images are actually imported.

**Comment by nanoandrew4** [comment]
Thank you for all the help, I managed to get it working in the end with the approach you suggested :)
